Fixed Rails 7.1 error due to `serialize` call with no `coder`:
> ArgumentError: missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`.

See https://github.com/rails/rails/pull/47463 for background on this change.